### ISSUE TITLE
use Ivy revision ranges in Dependencies.scala

### ISSUE THREAD

**Issue by performantdata** [typesafehub/scala-logging#41]
I get a warning from the `scala-maven-plugin` when building with your project, because the Scala version is different from the one I'm using:
```
[WARNING]  Expected all dependencies to require Scala version: 2.11.7
...
[WARNING]  com.typesafe.scala-logging.scala-logging_2.11:3.1.0 requires scala version 2.11.1
[WARNING] Multiple versions of scala libraries detected!
```
I'm guessing that this could be resolved, w/o any hackiness on my side, by setting the required revision in `Dependencies.scala` to `[2.11,2.12[`.

**Comment by analytically** [comment]
@eed3si9n woud this indeed be the case for SBT 0.13.11?

**Comment by eed3si9n** [comment]
@analytically Not sure what you mean. Are you asking:
-  if the same warning message as the Maven plugin would be shown if someone used scala-logging in sbt 0.13.11?
- or if this error message is caused by sbt 0.13.11?

**Comment by analytically** [comment]
No, just if setting [2.11,2.12[ for the scala-reflect version would resolve his warning.

**Comment by eed3si9n** [comment]
Using dynamic revisions and version range would invite more trouble for sbt/Ivy users. sbt would likely force the users of scala-logging to check the internet for the latest version. The situation with scala-reflect always confuses me because I don't know if binary compatibility among the minor versions are actually promised for scala-reflect or -compiler.

I am guessing the safest/ideal thing to do would be to align the scala-reflect and -library versions with the Scala compiler version that's used to build the app. (I don't know if that's what the Maven Scala plugin is going for) Instead of changing scala-logging or any other libraries, I think the build tools should allow the users to align those versions.
